### PR TITLE
Changes for Win32 building

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
Changes for building on Windows - please check they still work on Linux

* add `epicsShareFunc` to export the templates from the DLL
* change `interface` to `piface`  to avoid name clash

### CODE REVIEW

**Comment by exzombie** [comment]
Hello Freddie,

Thanks a lot! I checked and Linux build is fine with your changes. There are just two minor points left to address:
- The `__attribute__` mechanism is only used once, in the `addInitHook()` function, to silence a compiler warning. Instead of redefining `__attribute__`, I think it is more elegant to remove the "unused" attribute from the variable, and instead cast the variable to `void`, which achieves the same purpose in a portable way.
- The comment about `rand_r` should be updated: `rand_s` is not an alternative, but AFAICT, on Windows, `rand()` is sufficient, and it would be nice if the comment said so. And even if StackOverflow is wrong and `rand()` is not re-seeded on thread creation, the test app is just a development playground so we don't care.

**Comment by exzombie** [comment]
@FreddieAkeroyd @rerpha 

I've created an  [integration branch](/Cosylab/autoparamDriver/tree/stfc-integration) with your changes, plus a fix for the issue you found with more than one driver instance in a single IOC. I used the opportunity and switched to a newer mechanism for exporting DLL symbols. Would you please check that autoparam and ads modules still work on Windows?

**Comment by rerpha** [comment]
Thanks @exzombie , just looking now. is the API header generated at compile-time? I am having some issues compiling but it may just be my setup

**Comment by exzombie** [comment]
Yes, it is generated by `makeAPIheader.pl`. More details [here](https://github.com/epics-base/epics-base/pull/320).

**Comment by rerpha** [comment]
ah i see. we are on EPICS base 7.0.3.1 so thats why i cant build it - could you make it backwards compatible (ie use makeAPIheader.pl when available, fall back if not) please?

**Comment by FreddieAkeroyd** [comment]
Can you just include the file generated by `makeAPIheader.pl` in the source - i think that is what asyn is doing, with possibly a few other tweaks

**Comment by exzombie** [comment]
Good idea @FreddieAkeroyd, including a pre-built file appears to work in a quick test on linux with base 7.0.1. I pushed the change to the integration branch. The pre-built file is only used when `makeAPIheader.pl` is absent, which should give us forward compatibility.

**Comment by rerpha** [comment]
thanks @exzombie  - we had to modify it slightly as some of the epicsStdCalls were stopping us from compiling, but i think they might be superfluous anyway. Also there looked to be an endif in the header in the wrong place. have made https://github.com/Cosylab/autoparamDriver/pull/2 to merge our changes back into your stfc-integration branch

**Pull request merged**
