### PR TITLE
fix makefile endif in the wrong place and remove superfluous(?) epicsStdCalls

### PR DESCRIPTION
**Pull request by rerpha**

### CODE REVIEW

**Comment by rerpha** [comment]
if on windows you define epicsStdCall and then undefine it - seemed wrong? It looked like the endif was in the wrong place as i thought gnuc should be the only thing doing the undefine, but i might be wrong. either way it seems to compile for me on windows

**Comment by exzombie** [comment]
Ah, that's where the confusion originates. This block
```
#if !defined(epicsStdCall)
#  define epicsStdCall
#endif
```
is read as "if the `epicsStdCall` preprocessor symbol is not defined yet, define it now, but make it empty so that, when used, it expands into nothing". I expect that this is here for platforms that are not Windows: on Windows, it is previously defined to expand into `__stdcall`. Other platforms don't need that, but the symbol still needs to be defined, otherwise, it cannot be used. It just has to be empty.

I'm still confused though: when you say "it seems to compile for me", are you refering to the modified API header, or did you manage to build and run autoparam and ads modules with the *unmodified* API header?

**Comment by rerpha** [comment]
ok, fair enough, i can remove the header from the changes, i think all that is needed is just the removal of the stdcalls - it compiles for me with the unmodified API header, but needed the stdcalls to be removed to compile.

**Comment by exzombie** [comment]
Excellent! I'll merge both PRs then, and see about making a new release together with the ADS driver. Thanks a lot for your help!

**Pull request merged**
